Repository freeCodeCamp/devdocs, pull requests merged in 2019-07, with the labels that each got.

#942 Remove scope by clicking on it or by backspacing into it
  assets/javascripts/views/search/search.coffee
  assets/javascripts/views/search/search_scope.coffee
  assets/stylesheets/components/_header.scss
Labels: improvement

#848 Automatically generate public/docs/docs.json when it's needed
  lib/app.rb
  public/docs/docs.json
Labels: improvement

#831 Hide sidebar when mouse is outside the window
  assets/javascripts/views/sidebar/sidebar.coffee
Labels: improvement

#941 Fix single documentation search on Android
  assets/javascripts/lib/util.coffee
  assets/javascripts/views/search/search_scope.coffee
Labels: improvement

#975 Stop using an iframe for the GitHub star button
  assets/javascripts/templates/pages/root_tmpl.coffee.erb
Labels: improvement

#979 Cookie consent
  assets/javascripts/app/settings.coffee
  assets/javascripts/lib/page.coffee
  assets/javascripts/templates/notif_tmpl.coffee
  assets/javascripts/templates/pages/about_tmpl.coffee
  assets/javascripts/templates/pages/settings_tmpl.coffee
  assets/javascripts/tracking.js
  assets/javascripts/views/content/settings_page.coffee
  assets/javascripts/views/layout/document.coffee
  assets/stylesheets/components/_notif.scss
Labels: feature

#886 Add option to automatically download documentation
  assets/javascripts/app/app.coffee
  assets/javascripts/app/settings.coffee
  assets/javascripts/models/doc.coffee
  assets/javascripts/templates/pages/settings_tmpl.coffee
  assets/javascripts/views/content/settings_page.coffee
Labels: feature

#870 Automatically generate spritesheets
  Gemfile
  Gemfile.lock
  assets/images/.gitignore
  assets/images/docs-1.png
  assets/images/docs-1@2x.png
  assets/images/docs-2.png
  assets/images/docs-2@2x.png
  assets/stylesheets/application.css.scss
  assets/stylesheets/global/_icons.scss
  assets/stylesheets/global/_icons.scss.erb
  lib/app.rb
  lib/tasks/assets.thor
  lib/tasks/sprites.thor
  public/icons/docs-1.pxm
  public/icons/docs-1@2x.pxm
  public/icons/docs-2.pxm
  public/icons/docs-2@2x.pxm
  public/icons/docs/bluebird/16@2x.png
Labels: feature

#988 Upgrade Ruby and gems
  .ruby-version
  .travis.yml
  Gemfile
  Gemfile.lock
Labels: improvement

#977 update bash to 5.0
  lib/docs/scrapers/bash.rb
Labels: docs/update
